[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agno>=2.0.4",
    "exa-py>=1.15.6",
    "fastapi>=0.116.1",
    "openai>=1.107.2",
    "uvicorn>=0.35.0",
    "websockets>=15.0.1",
]
